"""initial

Revision ID: 34e1e3d1343d
Revises: 
Create Date: 2025-12-13 18:32:34.935253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e1e3d1343d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_task_participants_participant_id_fkey'), 'group_task_participants', type_='foreignkey')
    op.drop_constraint(op.f('group_task_participants_group_task_id_fkey'), 'group_task_participants', type_='foreignkey')
    op.create_foreign_key(None, 'group_task_participants', 'group_tasks', ['group_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_task_participants', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.add_column('group_tasks', sa.Column('edited', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('members_participants_members_id_fkey'), 'members_participants', type_='foreignkey')
    op.drop_constraint(op.f('members_participants_participants_id_fkey'), 'members_participants', type_='foreignkey')
    op.create_foreign_key(None, 'members_participants', 'members', ['members_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'members_participants', 'participants', ['participants_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('seen', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('sender_deleted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('receiver_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'receiver_deleted')
    op.drop_column('messages', 'sender_deleted')
    op.drop_column('messages', 'seen')
    op.drop_constraint(None, 'members_participants', type_='foreignkey')
    op.drop_constraint(None, 'members_participants', type_='foreignkey')
    op.create_foreign_key(op.f('members_participants_participants_id_fkey'), 'members_participants', 'participants', ['participants_id'], ['id'])
    op.create_foreign_key(op.f('members_participants_members_id_fkey'), 'members_participants', 'members', ['members_id'], ['id'])
    op.drop_column('group_tasks', 'edited')
    op.drop_constraint(None, 'group_task_participants', type_='foreignkey')
    op.drop_constraint(None, 'group_task_participants', type_='foreignkey')
    op.create_foreign_key(op.f('group_task_participants_group_task_id_fkey'), 'group_task_participants', 'group_tasks', ['group_task_id'], ['id'])
    op.create_foreign_key(op.f('group_task_participants_participant_id_fkey'), 'group_task_participants', 'participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###
