"""added indexes

Revision ID: 69bc07ba3aec
Revises: ed74373f9571
Create Date: 2026-02-14 21:00:32.421820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bc07ba3aec'
down_revision: Union[str, Sequence[str], None] = 'ed74373f9571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blogs_time_of_post'), 'blogs', ['time_of_post'], unique=False)
    op.create_index(op.f('ix_blogs_user_id'), 'blogs', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_blog_id'), 'comments', ['blog_id'], unique=False)
    op.create_index(op.f('ix_comments_time_of_post'), 'comments', ['time_of_post'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_contributions_group_id'), 'contributions', ['group_id'], unique=False)
    op.create_index(op.f('ix_contributions_grouptask_id'), 'contributions', ['grouptask_id'], unique=False)
    op.create_index(op.f('ix_contributions_time'), 'contributions', ['time'], unique=False)
    op.create_index(op.f('ix_contributions_user_id'), 'contributions', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_admins_group_id'), 'group_admins', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_admins_user_id'), 'group_admins', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_tasks_group_id'), 'group_tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_tasks_user_id'), 'group_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_members_group_id'), 'members', ['group_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_time_of_chat'), 'messages', ['time_of_chat'], unique=False)
    op.create_index(op.f('ix_opinion_votes_id'), 'opinion_votes', ['id'], unique=False)
    op.create_index(op.f('ix_opinions_group_id'), 'opinions', ['group_id'], unique=False)
    op.create_index(op.f('ix_opinions_task_id'), 'opinions', ['task_id'], unique=False)
    op.create_index(op.f('ix_opinions_user_id'), 'opinions', ['user_id'], unique=False)
    op.create_index(op.f('ix_participants_group_id'), 'participants', ['group_id'], unique=False)
    op.create_index(op.f('ix_participants_time_of_assignment'), 'participants', ['time_of_assignment'], unique=False)
    op.create_index(op.f('ix_reacts_time_of_reaction'), 'reacts', ['time_of_reaction'], unique=False)
    op.create_index(op.f('ix_reacts_user_id'), 'reacts', ['user_id'], unique=False)
    op.create_index(op.f('ix_shares_blog_id'), 'shares', ['blog_id'], unique=False)
    op.create_index(op.f('ix_shares_time_of_share'), 'shares', ['time_of_share'], unique=False)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_time_of_share'), table_name='shares')
    op.drop_index(op.f('ix_shares_blog_id'), table_name='shares')
    op.drop_index(op.f('ix_reacts_user_id'), table_name='reacts')
    op.drop_index(op.f('ix_reacts_time_of_reaction'), table_name='reacts')
    op.drop_index(op.f('ix_participants_time_of_assignment'), table_name='participants')
    op.drop_index(op.f('ix_participants_group_id'), table_name='participants')
    op.drop_index(op.f('ix_opinions_user_id'), table_name='opinions')
    op.drop_index(op.f('ix_opinions_task_id'), table_name='opinions')
    op.drop_index(op.f('ix_opinions_group_id'), table_name='opinions')
    op.drop_index(op.f('ix_opinion_votes_id'), table_name='opinion_votes')
    op.drop_index(op.f('ix_messages_time_of_chat'), table_name='messages')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_group_id'), table_name='members')
    op.drop_index(op.f('ix_group_tasks_user_id'), table_name='group_tasks')
    op.drop_index(op.f('ix_group_tasks_group_id'), table_name='group_tasks')
    op.drop_index(op.f('ix_group_admins_user_id'), table_name='group_admins')
    op.drop_index(op.f('ix_group_admins_group_id'), table_name='group_admins')
    op.drop_index(op.f('ix_contributions_user_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_time'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_grouptask_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_group_id'), table_name='contributions')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_time_of_post'), table_name='comments')
    op.drop_index(op.f('ix_comments_blog_id'), table_name='comments')
    op.drop_index(op.f('ix_blogs_user_id'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_time_of_post'), table_name='blogs')
    # ### end Alembic commands ###
