"""refactored share table

Revision ID: f46631d0aac2
Revises: 121e5891e58a
Create Date: 2026-01-09 16:45:07.207891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46631d0aac2'
down_revision: Union[str, Sequence[str], None] = '121e5891e58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shares_blog_id_fkey'), 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'blogs', ['blog_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key(op.f('shares_blog_id_fkey'), 'shares', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###
